### ISSUE TITLE
Package and install scripts

### ISSUE THREAD

**Issue by jack-h** [reeveress/monitor-control#3]
Create a setup.py to install the python package (library + scripts).
Ideally, all the scripts would be prefixed by some common string, for easy tab-completion in a terminal.

Eg.
hera_node_turn_on
hera_node_get_status
etc...

**Comment by reeveress** [comment]
I will need some help writing the setup.py file when you get back. I fixed
the argparse help, wrote a hera_node_get_status script and renamed other
scripts to tab friendly names.

**Comment by jack-h** [comment]
Excellent! Thanks.

I can talk to you about this next week. Otherwise Deepthi has done this kind of thing before.

**Comment by reeveress** [comment]
😢

**Comment by jack-h** [comment]
You're missing so much City Lodge.

**Comment by reeveress** [comment]
I’m having so much nostalgia right now 😭 wish I was there with you guys
